### ISSUE TITLE
Only pages router supported?

### ISSUE THREAD

**Issue by ReDev1L** [remorses/next-superjson#10]
```
/node_modules/next-superjson/dist/index.js:68
throw new Error("Couldn't find a `pages` directory. Please create one under the project root");
```
next dev output, i'm using app router.

**Comment by remorses** [comment]
Yes only pages is supported, you shouldn’t need this plugin for app, React serialization format already supports dates, etc

**Comment by ReDev1L** [comment]
> Yes only pages is supported, you shouldn’t need this plugin for app, React serialization format already supports dates, etc

If you pass data from server component to client component - React doesnt like Decimals and BigInts from Prisma

**Comment by remorses** [comment]
React RSC should support BigInt

**Comment by samtgarson** [comment]
@remorses the benefit of Superjson is that it can serialize _any_ complex object, including custom classes. React serialization only supports a very limited set of objects. It would be very beneficial to have this plugin work for the App Dir 🙇
