### ISSUE TITLE
withSuperjson ignores next configs

### ISSUE THREAD

**Issue by michaelpomogajko** [remorses/next-superjson#3]
Running `next build` with the withSuperjson wrapper function fails because of ts errors, meaning it ignores the config for nextjs.
When removing the wrapper function, it works as expected

```js
const { withSuperjson } = require('next-superjson')

const config = {
  reactStrictMode: true,
  swcMinify: true,
  eslint: {
    ignoreDuringBuilds: true
  },
  typescript: {
    ignoreBuildErrors: true
  }
}

module.exports = withSuperjson(config);
```

**Comment by remorses** [comment]
You have to call it like this

`module.exports = withSuperjson()({})`

I kept a first parameter to pass options to superjson and not pollute the config object
