### ISSUE TITLE
`getLayout` does not work with `getStaticProps`

### ISSUE THREAD

**Issue by sanny-io** [remorses/next-superjson#4]
When following [this guide](https://nextjs.org/docs/basic-features/layouts#with-typescript) and specifying a `getStaticProps` function in my page that uses a layout, the page is rendered, but is not wrapped in the layout.

After removing the `getStaticProps` function or after removing `withSuperjson` from my Next.js configuration, the issue goes away, and both the page and layout are rendered.

I'm using Next.js 12.1.4 and next-superjson 0.0.2

**Comment by Haberkamp** [comment]
I can confirm the exact same issue

**Comment by merthanmerter** [comment]
can confirm. It also causes a full reload.

**Comment by merthanmerter** [comment]
https://github.com/blitz-js/next-superjson-plugin/issues/18

**Comment by remorses** [comment]
Should be fixed in latest version thanks to migration to the SWC plugin
