### ISSUE TITLE
Support Next.js 13 Server Components

### ISSUE THREAD

**Issue by nyarthan** [remorses/next-superjson#7]
When passing objects from Server Components to Client Components that contain e.g. a Date you get following Warning:
```sh
Warning: Only plain objects can be passed to Client Components from Server Components. Date objects are not supported.
  {createdAt: Date}
              ^^^^
```
The corresponding data in the Client Component would than be a stringified version of the object. This is arguably worse than Next.js 12 throwing an error.

**Comment by AryanJ-NYC** [comment]
Leaving this here for the next person: https://github.com/blitz-js/next-superjson-plugin
