### ISSUE TITLE
Stopped working in "next": "^13.0.6"

### ISSUE THREAD

**Issue by elie222** [remorses/next-superjson#8]
It was fine on Next 13.0.3.

Error is object not serialisable.

I've moved to this for now:
https://www.npmjs.com/package/babel-plugin-superjson-next
Although this disables SWC.

**Comment by remorses** [comment]
You can also try https://github.com/blitz-js/next-superjson-plugin which keeps swc support

**Comment by elie222** [comment]
Thanks. Having tried again I think it was Sentry that was causing the errors in the end.
